### ISSUE TITLE
Problem with inference.py

### ISSUE THREAD

**Issue by peterwilson3912** [sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection#11]
Hi! I did run `inference.py`. However, I got this error when I run this code:

```
E:\pro1\Scripts\python.exe E:/Research/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/inference.py
  0%|          | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "E:/Research/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/inference.py", line 104, in <module>
    calculate_mae(rt_args)
  File "E:/Research/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/inference.py", line 91, in calculate_mae
    for batch_idx, (inp_imgs, gt_masks) in enumerate(tqdm.tqdm(test_dataloader), start=1):
  File "E:\pro1\lib\site-packages\tqdm\std.py", line 1127, in __iter__
    for obj in iterable:
  File "E:\pro1\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "E:\pro1\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "E:\pro1\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "E:\pro1\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "E:\pro1\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\pro1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\pro1\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Research\PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection\src\dataloader.py", line 163, in __getitem__
    mask_img = cv2.imread(self.out_files[idx], 0)
IndexError: list index out of range


Process finished with exit code 1
```
You provide initial 3 images in `./data/DUTS/DUTS-TE/DUTS-TE-Image`. I just add two more my own images in this folder and then run `inference.py`. It seems the number in masks and images folder should be the same. I don't know why.

Would you please help me with this? Thank you so much for your help!

**Comment by sairajk** [comment]
There are actually two functions that are being called when you run `inference.py`:

1. `calculate_mae`: This function calculates the Mean Average Error (MAE), which requires both input and the corresponding ground truth images. 
2. `run_inference`: This function actually does the inference, this does not require any ground-truth masks.

To just run the inference without calculating MAE, comment this [line](https://github.com/sairajk/PyTorch-Pyramid-Feature-Attention-Network-for-Saliency-Detection/blob/master/inference.py#L104)
